/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as CleaningIndexRouteImport } from './routes/cleaning/index'
import { Route as CleanerIndexRouteImport } from './routes/cleaner/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AiImportIndexRouteImport } from './routes/ai-import/index'
import { Route as SettingsTeamRouteImport } from './routes/settings/team'
import { Route as PropertiesNewRouteImport } from './routes/properties/new'
import { Route as PropertiesGanttRouteImport } from './routes/properties/gantt'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties/$propertyId'
import { Route as CleaningNewRouteImport } from './routes/cleaning/new'
import { Route as CleaningChecklistsRouteImport } from './routes/cleaning/checklists'
import { Route as CleaningTaskIdRouteImport } from './routes/cleaning/$taskId'
import { Route as CleanerTaskIdRouteImport } from './routes/cleaner/$taskId'
import { Route as BookingsTodayRouteImport } from './routes/bookings/today'
import { Route as BookingsNewRouteImport } from './routes/bookings/new'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings/$bookingId'
import { Route as AiImportJobIdRouteImport } from './routes/ai-import/$jobId'
import { Route as PropertiesPropertyIdIndexRouteImport } from './routes/properties/$propertyId/index'
import { Route as BookingsBookingIdIndexRouteImport } from './routes/bookings/$bookingId/index'
import { Route as PropertiesPropertyIdEditRouteImport } from './routes/properties/$propertyId/edit'
import { Route as BookingsBookingIdEditRouteImport } from './routes/bookings/$bookingId/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleaningIndexRoute = CleaningIndexRouteImport.update({
  id: '/cleaning/',
  path: '/cleaning/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanerIndexRoute = CleanerIndexRouteImport.update({
  id: '/cleaner/',
  path: '/cleaner/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiImportIndexRoute = AiImportIndexRouteImport.update({
  id: '/ai-import/',
  path: '/ai-import/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesNewRoute = PropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesGanttRoute = PropertiesGanttRouteImport.update({
  id: '/properties/gantt',
  path: '/properties/gantt',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const CleaningNewRoute = CleaningNewRouteImport.update({
  id: '/cleaning/new',
  path: '/cleaning/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CleaningChecklistsRoute = CleaningChecklistsRouteImport.update({
  id: '/cleaning/checklists',
  path: '/cleaning/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const CleaningTaskIdRoute = CleaningTaskIdRouteImport.update({
  id: '/cleaning/$taskId',
  path: '/cleaning/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanerTaskIdRoute = CleanerTaskIdRouteImport.update({
  id: '/cleaner/$taskId',
  path: '/cleaner/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsTodayRoute = BookingsTodayRouteImport.update({
  id: '/bookings/today',
  path: '/bookings/today',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AiImportJobIdRoute = AiImportJobIdRouteImport.update({
  id: '/ai-import/$jobId',
  path: '/ai-import/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdIndexRoute =
  PropertiesPropertyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PropertiesPropertyIdRoute,
  } as any)
const BookingsBookingIdIndexRoute = BookingsBookingIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingsBookingIdRoute,
} as any)
const PropertiesPropertyIdEditRoute =
  PropertiesPropertyIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => PropertiesPropertyIdRoute,
  } as any)
const BookingsBookingIdEditRoute = BookingsBookingIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BookingsBookingIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai-import/$jobId': typeof AiImportJobIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/today': typeof BookingsTodayRoute
  '/cleaner/$taskId': typeof CleanerTaskIdRoute
  '/cleaning/$taskId': typeof CleaningTaskIdRoute
  '/cleaning/checklists': typeof CleaningChecklistsRoute
  '/cleaning/new': typeof CleaningNewRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRouteWithChildren
  '/properties/gantt': typeof PropertiesGanttRoute
  '/properties/new': typeof PropertiesNewRoute
  '/settings/team': typeof SettingsTeamRoute
  '/ai-import/': typeof AiImportIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/cleaner/': typeof CleanerIndexRoute
  '/cleaning/': typeof CleaningIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/bookings/$bookingId/edit': typeof BookingsBookingIdEditRoute
  '/properties/$propertyId/edit': typeof PropertiesPropertyIdEditRoute
  '/bookings/$bookingId/': typeof BookingsBookingIdIndexRoute
  '/properties/$propertyId/': typeof PropertiesPropertyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai-import/$jobId': typeof AiImportJobIdRoute
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/today': typeof BookingsTodayRoute
  '/cleaner/$taskId': typeof CleanerTaskIdRoute
  '/cleaning/$taskId': typeof CleaningTaskIdRoute
  '/cleaning/checklists': typeof CleaningChecklistsRoute
  '/cleaning/new': typeof CleaningNewRoute
  '/properties/gantt': typeof PropertiesGanttRoute
  '/properties/new': typeof PropertiesNewRoute
  '/settings/team': typeof SettingsTeamRoute
  '/ai-import': typeof AiImportIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/cleaner': typeof CleanerIndexRoute
  '/cleaning': typeof CleaningIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/bookings/$bookingId/edit': typeof BookingsBookingIdEditRoute
  '/properties/$propertyId/edit': typeof PropertiesPropertyIdEditRoute
  '/bookings/$bookingId': typeof BookingsBookingIdIndexRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai-import/$jobId': typeof AiImportJobIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/today': typeof BookingsTodayRoute
  '/cleaner/$taskId': typeof CleanerTaskIdRoute
  '/cleaning/$taskId': typeof CleaningTaskIdRoute
  '/cleaning/checklists': typeof CleaningChecklistsRoute
  '/cleaning/new': typeof CleaningNewRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRouteWithChildren
  '/properties/gantt': typeof PropertiesGanttRoute
  '/properties/new': typeof PropertiesNewRoute
  '/settings/team': typeof SettingsTeamRoute
  '/ai-import/': typeof AiImportIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/cleaner/': typeof CleanerIndexRoute
  '/cleaning/': typeof CleaningIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/bookings/$bookingId/edit': typeof BookingsBookingIdEditRoute
  '/properties/$propertyId/edit': typeof PropertiesPropertyIdEditRoute
  '/bookings/$bookingId/': typeof BookingsBookingIdIndexRoute
  '/properties/$propertyId/': typeof PropertiesPropertyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/ai-import/$jobId'
    | '/bookings/$bookingId'
    | '/bookings/new'
    | '/bookings/today'
    | '/cleaner/$taskId'
    | '/cleaning/$taskId'
    | '/cleaning/checklists'
    | '/cleaning/new'
    | '/properties/$propertyId'
    | '/properties/gantt'
    | '/properties/new'
    | '/settings/team'
    | '/ai-import/'
    | '/analytics/'
    | '/bookings/'
    | '/cleaner/'
    | '/cleaning/'
    | '/properties/'
    | '/settings/'
    | '/bookings/$bookingId/edit'
    | '/properties/$propertyId/edit'
    | '/bookings/$bookingId/'
    | '/properties/$propertyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/ai-import/$jobId'
    | '/bookings/new'
    | '/bookings/today'
    | '/cleaner/$taskId'
    | '/cleaning/$taskId'
    | '/cleaning/checklists'
    | '/cleaning/new'
    | '/properties/gantt'
    | '/properties/new'
    | '/settings/team'
    | '/ai-import'
    | '/analytics'
    | '/bookings'
    | '/cleaner'
    | '/cleaning'
    | '/properties'
    | '/settings'
    | '/bookings/$bookingId/edit'
    | '/properties/$propertyId/edit'
    | '/bookings/$bookingId'
    | '/properties/$propertyId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/ai-import/$jobId'
    | '/bookings/$bookingId'
    | '/bookings/new'
    | '/bookings/today'
    | '/cleaner/$taskId'
    | '/cleaning/$taskId'
    | '/cleaning/checklists'
    | '/cleaning/new'
    | '/properties/$propertyId'
    | '/properties/gantt'
    | '/properties/new'
    | '/settings/team'
    | '/ai-import/'
    | '/analytics/'
    | '/bookings/'
    | '/cleaner/'
    | '/cleaning/'
    | '/properties/'
    | '/settings/'
    | '/bookings/$bookingId/edit'
    | '/properties/$propertyId/edit'
    | '/bookings/$bookingId/'
    | '/properties/$propertyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AiImportJobIdRoute: typeof AiImportJobIdRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRouteWithChildren
  BookingsNewRoute: typeof BookingsNewRoute
  BookingsTodayRoute: typeof BookingsTodayRoute
  CleanerTaskIdRoute: typeof CleanerTaskIdRoute
  CleaningTaskIdRoute: typeof CleaningTaskIdRoute
  CleaningChecklistsRoute: typeof CleaningChecklistsRoute
  CleaningNewRoute: typeof CleaningNewRoute
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRouteWithChildren
  PropertiesGanttRoute: typeof PropertiesGanttRoute
  PropertiesNewRoute: typeof PropertiesNewRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  AiImportIndexRoute: typeof AiImportIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  CleanerIndexRoute: typeof CleanerIndexRoute
  CleaningIndexRoute: typeof CleaningIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning/': {
      id: '/cleaning/'
      path: '/cleaning'
      fullPath: '/cleaning/'
      preLoaderRoute: typeof CleaningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaner/': {
      id: '/cleaner/'
      path: '/cleaner'
      fullPath: '/cleaner/'
      preLoaderRoute: typeof CleanerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-import/': {
      id: '/ai-import/'
      path: '/ai-import'
      fullPath: '/ai-import/'
      preLoaderRoute: typeof AiImportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/new': {
      id: '/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof PropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/gantt': {
      id: '/properties/gantt'
      path: '/properties/gantt'
      fullPath: '/properties/gantt'
      preLoaderRoute: typeof PropertiesGanttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning/new': {
      id: '/cleaning/new'
      path: '/cleaning/new'
      fullPath: '/cleaning/new'
      preLoaderRoute: typeof CleaningNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning/checklists': {
      id: '/cleaning/checklists'
      path: '/cleaning/checklists'
      fullPath: '/cleaning/checklists'
      preLoaderRoute: typeof CleaningChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning/$taskId': {
      id: '/cleaning/$taskId'
      path: '/cleaning/$taskId'
      fullPath: '/cleaning/$taskId'
      preLoaderRoute: typeof CleaningTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaner/$taskId': {
      id: '/cleaner/$taskId'
      path: '/cleaner/$taskId'
      fullPath: '/cleaner/$taskId'
      preLoaderRoute: typeof CleanerTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/today': {
      id: '/bookings/today'
      path: '/bookings/today'
      fullPath: '/bookings/today'
      preLoaderRoute: typeof BookingsTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-import/$jobId': {
      id: '/ai-import/$jobId'
      path: '/ai-import/$jobId'
      fullPath: '/ai-import/$jobId'
      preLoaderRoute: typeof AiImportJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId/': {
      id: '/properties/$propertyId/'
      path: '/'
      fullPath: '/properties/$propertyId/'
      preLoaderRoute: typeof PropertiesPropertyIdIndexRouteImport
      parentRoute: typeof PropertiesPropertyIdRoute
    }
    '/bookings/$bookingId/': {
      id: '/bookings/$bookingId/'
      path: '/'
      fullPath: '/bookings/$bookingId/'
      preLoaderRoute: typeof BookingsBookingIdIndexRouteImport
      parentRoute: typeof BookingsBookingIdRoute
    }
    '/properties/$propertyId/edit': {
      id: '/properties/$propertyId/edit'
      path: '/edit'
      fullPath: '/properties/$propertyId/edit'
      preLoaderRoute: typeof PropertiesPropertyIdEditRouteImport
      parentRoute: typeof PropertiesPropertyIdRoute
    }
    '/bookings/$bookingId/edit': {
      id: '/bookings/$bookingId/edit'
      path: '/edit'
      fullPath: '/bookings/$bookingId/edit'
      preLoaderRoute: typeof BookingsBookingIdEditRouteImport
      parentRoute: typeof BookingsBookingIdRoute
    }
  }
}

interface BookingsBookingIdRouteChildren {
  BookingsBookingIdEditRoute: typeof BookingsBookingIdEditRoute
  BookingsBookingIdIndexRoute: typeof BookingsBookingIdIndexRoute
}

const BookingsBookingIdRouteChildren: BookingsBookingIdRouteChildren = {
  BookingsBookingIdEditRoute: BookingsBookingIdEditRoute,
  BookingsBookingIdIndexRoute: BookingsBookingIdIndexRoute,
}

const BookingsBookingIdRouteWithChildren =
  BookingsBookingIdRoute._addFileChildren(BookingsBookingIdRouteChildren)

interface PropertiesPropertyIdRouteChildren {
  PropertiesPropertyIdEditRoute: typeof PropertiesPropertyIdEditRoute
  PropertiesPropertyIdIndexRoute: typeof PropertiesPropertyIdIndexRoute
}

const PropertiesPropertyIdRouteChildren: PropertiesPropertyIdRouteChildren = {
  PropertiesPropertyIdEditRoute: PropertiesPropertyIdEditRoute,
  PropertiesPropertyIdIndexRoute: PropertiesPropertyIdIndexRoute,
}

const PropertiesPropertyIdRouteWithChildren =
  PropertiesPropertyIdRoute._addFileChildren(PropertiesPropertyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AiImportJobIdRoute: AiImportJobIdRoute,
  BookingsBookingIdRoute: BookingsBookingIdRouteWithChildren,
  BookingsNewRoute: BookingsNewRoute,
  BookingsTodayRoute: BookingsTodayRoute,
  CleanerTaskIdRoute: CleanerTaskIdRoute,
  CleaningTaskIdRoute: CleaningTaskIdRoute,
  CleaningChecklistsRoute: CleaningChecklistsRoute,
  CleaningNewRoute: CleaningNewRoute,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRouteWithChildren,
  PropertiesGanttRoute: PropertiesGanttRoute,
  PropertiesNewRoute: PropertiesNewRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  AiImportIndexRoute: AiImportIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  CleanerIndexRoute: CleanerIndexRoute,
  CleaningIndexRoute: CleaningIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
